// @generated
// This file is @generated by prost-build.
// ── Shared messages ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub plan: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub trial_started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub trial_ends_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="7")]
    pub trial_used: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub role: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub org: ::core::option::Option<OrgInfo>,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, optional, tag="7")]
    pub accent_color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="8")]
    pub email_verified: bool,
}
// ── Login ─────────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub turnstile_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<UserInfo>,
    /// session_id is returned so non-browser clients can use Bearer auth.
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
}
// ── Logout ────────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
}
// ── GetMe ─────────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMeResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<UserInfo>,
}
// ── Register ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag="1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub org_name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub turnstile_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<UserInfo>,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub pending_verification: bool,
}
// ── CSRF Token ────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCsrfTokenRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCsrfTokenResponse {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
// ── Forgot Password ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgotPasswordRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForgotPasswordResponse {
}
// ── Reset Password ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResetPasswordRequest {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResetPasswordResponse {
}
// ── Verify Email ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyEmailRequest {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VerifyEmailResponse {
    #[prost(message, optional, tag="1")]
    pub user: ::core::option::Option<UserInfo>,
    #[prost(string, tag="2")]
    pub session_id: ::prost::alloc::string::String,
}
// ── Resend Verification ──────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResendVerificationRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResendVerificationResponse {
}
// ── OAuth Providers ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OAuthAccountInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub provider: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub provider_user_id: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProvidersRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersResponse {
    #[prost(message, repeated, tag="1")]
    pub providers: ::prost::alloc::vec::Vec<OAuthAccountInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnlinkProviderRequest {
    #[prost(string, tag="1")]
    pub provider: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnlinkProviderResponse {
}
// ── Subscription ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SubscriptionInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, optional, tag="4")]
    pub platform_subscription_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub platform_product_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="6")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub current_period_start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub current_period_end: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="9")]
    pub cancel_at_period_end: bool,
    #[prost(message, optional, tag="10")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="11")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag="12")]
    pub seats: i32,
}
// ── Get Status ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBillingStatusRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetBillingStatusResponse {
    #[prost(string, tag="1")]
    pub plan: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub effective_plan: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub trial_ends_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, optional, tag="4")]
    pub trial_days_remaining: ::core::option::Option<i32>,
    #[prost(bool, tag="5")]
    pub trial_used: bool,
    #[prost(message, optional, tag="6")]
    pub active_subscription: ::core::option::Option<SubscriptionInfo>,
}
// ── Start Trial ──────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartTrialRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartTrialResponse {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub plan: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub trial_started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub trial_ends_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="7")]
    pub trial_used: bool,
}
// ── Record Subscription ──────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordSubscriptionRequest {
    #[prost(string, tag="1")]
    pub platform: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub platform_subscription_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub platform_product_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub platform_receipt: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub current_period_start: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub current_period_end: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecordSubscriptionResponse {
    #[prost(message, optional, tag="1")]
    pub subscription: ::core::option::Option<SubscriptionInfo>,
}
// ── Cancel Subscription ──────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelSubscriptionRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelSubscriptionResponse {
}
// ── Creem Checkout ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCreemCheckoutRequest {
    #[prost(string, tag="1")]
    pub plan: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub seats: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCreemCheckoutResponse {
    #[prost(string, tag="1")]
    pub checkout_url: ::prost::alloc::string::String,
}
// ── Creem Portal ─────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCreemPortalRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCreemPortalResponse {
    #[prost(string, tag="1")]
    pub portal_url: ::prost::alloc::string::String,
}
// ── Creem Update Seats ────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateCreemSeatsRequest {
    #[prost(int32, tag="1")]
    pub seats: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateCreemSeatsResponse {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyElement {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="8")]
    pub technology_links: ::prost::alloc::vec::Vec<DependencyTechnologyLink>,
    #[prost(string, repeated, tag="9")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="13")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="14")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="15")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DependencyTechnologyLink {
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub label: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub is_primary_icon: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DependencyConnector {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub view_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source_element_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub target_element_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub relationship: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub direction: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub style: ::prost::alloc::string::String,
    #[prost(string, optional, tag="10")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub source_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub target_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="14")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDependenciesRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListDependenciesResponse {
    #[prost(message, repeated, tag="1")]
    pub elements: ::prost::alloc::vec::Vec<DependencyElement>,
    #[prost(message, repeated, tag="2")]
    pub connectors: ::prost::alloc::vec::Vec<DependencyConnector>,
}
// ── Authorize ────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceAuthorizeRequest {
    #[prost(string, tag="1")]
    pub client_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceAuthorizeResponse {
    #[prost(string, tag="1")]
    pub device_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_code: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub verification_uri: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub verification_uri_complete: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub expires_in: i32,
    #[prost(int32, tag="6")]
    pub interval: i32,
}
// ── Poll Token ───────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DevicePollTokenRequest {
    #[prost(string, tag="1")]
    pub device_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DevicePollTokenResponse {
    /// Set when approved and key consumed.
    #[prost(string, tag="1")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    /// Set when still pending or error.
    #[prost(string, tag="3")]
    pub error: ::prost::alloc::string::String,
}
// ── Get Code Info ────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCodeInfoRequest {
    #[prost(string, tag="1")]
    pub user_code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetCodeInfoResponse {
    #[prost(string, tag="1")]
    pub user_code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub client_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
// ── Confirm ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceConfirmRequest {
    #[prost(string, tag="1")]
    pub user_code: ::prost::alloc::string::String,
    /// "approve" or "deny"
    #[prost(string, tag="2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub org_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceConfirmResponse {
}
// ── Share View ───────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareViewRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(string, optional, tag="2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="3")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShareViewResponse {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
}
// ─── Export messages ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportOrganizationRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="2")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExportOrganizationResponse {
    #[prost(message, repeated, tag="1")]
    pub views: ::prost::alloc::vec::Vec<View>,
    #[prost(message, repeated, tag="2")]
    pub elements: ::prost::alloc::vec::Vec<Element>,
    #[prost(message, repeated, tag="3")]
    pub connectors: ::prost::alloc::vec::Vec<Connector>,
    #[prost(message, repeated, tag="4")]
    pub navigations: ::prost::alloc::vec::Vec<ElementNavigation>,
    #[prost(message, repeated, tag="5")]
    pub placements: ::prost::alloc::vec::Vec<ElementPlacement>,
    #[prost(message, repeated, tag="6")]
    pub layers: ::prost::alloc::vec::Vec<ViewLayer>,
}
// ─── ApplyPlan messages ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlanViewPlacement {
    /// Parent element ref that owns the target canonical diagram.
    /// Use "root" for the synthetic workspace root view.
    #[prost(string, tag="1")]
    pub parent_ref: ::prost::alloc::string::String,
    #[prost(double, optional, tag="2")]
    pub position_x: ::core::option::Option<f64>,
    #[prost(double, optional, tag="3")]
    pub position_y: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlanElement {
    #[prost(string, tag="1")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="8")]
    pub technology_links: ::prost::alloc::vec::Vec<TechnologyLink>,
    #[prost(string, repeated, tag="9")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="10")]
    pub placements: ::prost::alloc::vec::Vec<PlanViewPlacement>,
    #[prost(int32, optional, tag="11")]
    pub id: ::core::option::Option<i32>,
    #[prost(message, optional, tag="12")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, optional, tag="13")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="14")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="15")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="16")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="17")]
    pub has_view: bool,
    #[prost(string, optional, tag="18")]
    pub view_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="19")]
    pub view_id: ::core::option::Option<i32>,
    #[prost(message, optional, tag="20")]
    pub view_updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlanConnector {
    #[prost(string, tag="1")]
    pub r#ref: ::prost::alloc::string::String,
    /// Owning view ref. Use "root" for the synthetic workspace root view.
    #[prost(string, tag="2")]
    pub view_ref: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub source_element_ref: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub target_element_ref: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub relationship: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="8")]
    pub direction: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="9")]
    pub style: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub source_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub target_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="13")]
    pub id: ::core::option::Option<i32>,
    #[prost(message, optional, tag="14")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyPlanRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub elements: ::prost::alloc::vec::Vec<PlanElement>,
    #[prost(message, repeated, tag="3")]
    pub connectors: ::prost::alloc::vec::Vec<PlanConnector>,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="6")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. If true, only return plan and conflicts without applying.
    #[prost(bool, optional, tag="7")]
    pub dry_run: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlanSummary {
    #[prost(int32, tag="1")]
    pub elements_planned: i32,
    #[prost(int32, tag="2")]
    pub elements_created: i32,
    #[prost(int32, tag="3")]
    pub views_planned: i32,
    #[prost(int32, tag="4")]
    pub views_created: i32,
    #[prost(int32, tag="5")]
    pub connectors_planned: i32,
    #[prost(int32, tag="6")]
    pub connectors_created: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlanDriftItem {
    /// "element" | "view" | "connector"
    #[prost(string, tag="1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkspaceVersion {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// "cli" or "frontend"
    #[prost(string, tag="4")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="5")]
    pub parent_version_id: ::core::option::Option<i32>,
    #[prost(int32, tag="6")]
    pub view_count: i32,
    #[prost(int32, tag="7")]
    pub element_count: i32,
    #[prost(int32, tag="8")]
    pub connector_count: i32,
    #[prost(int32, tag="9")]
    pub navigation_count: i32,
    #[prost(string, optional, tag="10")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub workspace_hash: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResourceMetadata {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(message, optional, tag="2")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlanConflictItem {
    /// "element" | "view" | "connector"
    #[prost(string, tag="1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub local_updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="4")]
    pub remote_updated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// "local_newer" | "remote_newer" | "unknown"
    #[prost(string, tag="5")]
    pub resolution_hint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyPlanElementResult {
    #[prost(string, tag="1")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub canonical_ref: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub id: i32,
    #[prost(message, optional, tag="4")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApplyPlanConnectorResult {
    #[prost(string, tag="1")]
    pub r#ref: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub canonical_ref: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub id: i32,
    #[prost(message, optional, tag="4")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyPlanResponse {
    #[prost(message, repeated, tag="1")]
    pub created_elements: ::prost::alloc::vec::Vec<Element>,
    #[prost(message, repeated, tag="2")]
    pub created_views: ::prost::alloc::vec::Vec<ViewSummary>,
    #[prost(message, repeated, tag="3")]
    pub created_placements: ::prost::alloc::vec::Vec<ElementPlacement>,
    #[prost(message, repeated, tag="4")]
    pub created_connectors: ::prost::alloc::vec::Vec<Connector>,
    #[prost(message, optional, tag="5")]
    pub summary: ::core::option::Option<PlanSummary>,
    #[prost(message, repeated, tag="6")]
    pub drift: ::prost::alloc::vec::Vec<PlanDriftItem>,
    #[prost(message, optional, tag="7")]
    pub version: ::core::option::Option<WorkspaceVersion>,
    #[prost(map="string, message", tag="8")]
    pub element_metadata: ::std::collections::HashMap<::prost::alloc::string::String, ResourceMetadata>,
    #[prost(map="string, message", tag="9")]
    pub view_metadata: ::std::collections::HashMap<::prost::alloc::string::String, ResourceMetadata>,
    #[prost(map="string, message", tag="10")]
    pub connector_metadata: ::std::collections::HashMap<::prost::alloc::string::String, ResourceMetadata>,
    #[prost(message, repeated, tag="11")]
    pub conflicts: ::prost::alloc::vec::Vec<PlanConflictItem>,
    #[prost(message, repeated, tag="12")]
    pub element_results: ::prost::alloc::vec::Vec<ApplyPlanElementResult>,
    #[prost(message, repeated, tag="13")]
    pub connector_results: ::prost::alloc::vec::Vec<ApplyPlanConnectorResult>,
}
// ─── Request messages ────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateViewRequest {
    /// Required. UUID of the organisation that owns this view.
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Required. Human-readable name of the view.
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// Optional. Longer description of the view.
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Label that describes the abstraction level (e.g. "System",
    /// "Container", "Component").
    #[prost(string, optional, tag="4")]
    pub level_label: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Integer ID of an existing element that owns this view.
    #[prost(int32, optional, tag="5")]
    pub owner_element_id: ::core::option::Option<i32>,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="6")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
// ─── Response messages ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateViewResponse {
    #[prost(message, optional, tag="1")]
    pub view: ::core::option::Option<View>,
}
// ─── Domain types ────────────────────────────────────────────────────────────

/// Element represents an element in the global registry (elements table).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Element {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="4")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="8")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="9")]
    pub technology_links: ::prost::alloc::vec::Vec<TechnologyLink>,
    #[prost(string, repeated, tag="10")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="12")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, optional, tag="13")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="14")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="15")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="16")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="17")]
    pub has_view: bool,
    #[prost(string, optional, tag="18")]
    pub view_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="19")]
    pub r#ref: ::prost::alloc::string::String,
}
/// ViewSummary represents a view in the workspace tree.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ViewSummary {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="3")]
    pub owner_element_id: ::core::option::Option<i32>,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="6")]
    pub is_root: bool,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// ElementPlacement represents an element's position on a specific diagram.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ElementPlacement {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub view_id: i32,
    #[prost(int32, tag="3")]
    pub element_id: i32,
    #[prost(double, tag="4")]
    pub position_x: f64,
    #[prost(double, tag="5")]
    pub position_y: f64,
}
/// PlacedElement is an element placement with denormalised element data for
/// canvas rendering.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlacedElement {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub view_id: i32,
    #[prost(int32, tag="3")]
    pub element_id: i32,
    #[prost(double, tag="4")]
    pub position_x: f64,
    #[prost(double, tag="5")]
    pub position_y: f64,
    #[prost(string, tag="6")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="7")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="8")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="9")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="12")]
    pub technology_links: ::prost::alloc::vec::Vec<TechnologyLink>,
    #[prost(string, repeated, tag="13")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="14")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="15")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="16")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="17")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
}
/// Connector represents a directed connection between two elements on a view.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Connector {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub view_id: i32,
    #[prost(int32, tag="3")]
    pub source_element_id: i32,
    #[prost(int32, tag="4")]
    pub target_element_id: i32,
    #[prost(string, optional, tag="5")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub relationship: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub direction: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub style: ::prost::alloc::string::String,
    #[prost(string, optional, tag="10")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub source_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub target_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="13")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="14")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// ElementNavigation represents an element-to-view navigation link.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ElementNavigation {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
    #[prost(int32, tag="3")]
    pub from_view_id: i32,
    #[prost(int32, tag="4")]
    pub to_view_id: i32,
}
/// ViewContent holds all placed elements and connectors for a single view.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewContent {
    #[prost(message, repeated, tag="1")]
    pub placements: ::prost::alloc::vec::Vec<PlacedElement>,
    #[prost(message, repeated, tag="2")]
    pub connectors: ::prost::alloc::vec::Vec<Connector>,
}
// ─── Domain types ────────────────────────────────────────────────────────────

/// View represents a view record.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct View {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub level_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag="6")]
    pub parent_view_id: ::core::option::Option<i32>,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="8")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, tag="9")]
    pub level: i32,
    #[prost(message, repeated, tag="10")]
    pub children: ::prost::alloc::vec::Vec<View>,
    #[prost(int32, tag="11")]
    pub depth: i32,
    #[prost(int32, optional, tag="12")]
    pub owner_element_id: ::core::option::Option<i32>,
}
// ─── Delete request/response messages ────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteViewRequest {
    /// Required. UUID of the organisation that owns the view.
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Required. Integer ID of the view to delete.
    #[prost(int32, tag="2")]
    pub view_id: i32,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="3")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteViewResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementRequest {
    /// Required. UUID of the organisation that owns the element.
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Required. Integer ID of the element to delete.
    #[prost(int32, tag="2")]
    pub element_id: i32,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="3")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConnectorRequest {
    /// Required. UUID of the organisation (used for ownership verification).
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Required. Integer ID of the connector to delete.
    #[prost(int32, tag="2")]
    pub connector_id: i32,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="3")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteConnectorResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementNavigationRequest {
    /// Required. UUID of the organisation (used for ownership verification).
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Required. Integer ID of the element navigation to delete.
    #[prost(int32, tag="2")]
    pub navigation_id: i32,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="3")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementNavigationResponse {
}
/// TechnologyLink is one entry in elements.technology_links (JSONB array,
/// max 3 per element).
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TechnologyLink {
    /// "catalog" (uses a well-known slug) or "custom" (user-provided label only).
    #[prost(string, tag="1")]
    pub r#type: ::prost::alloc::string::String,
    /// Required for type="catalog".  Identifies the technology in the icon catalog.
    #[prost(string, optional, tag="2")]
    pub slug: ::core::option::Option<::prost::alloc::string::String>,
    /// Required.  Human-readable display label.
    #[prost(string, tag="3")]
    pub label: ::prost::alloc::string::String,
    /// When true this technology's icon is used as the primary element icon.
    #[prost(bool, tag="4")]
    pub is_primary_icon: bool,
}
// ─── Browser-facing request/response messages ────────────────────────────────

// ── Views ────────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListViewsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListViewsResponse {
    #[prost(message, repeated, tag="1")]
    pub views: ::prost::alloc::vec::Vec<View>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetViewRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetViewResponse {
    #[prost(message, optional, tag="1")]
    pub view: ::core::option::Option<View>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateViewRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub level_label: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateViewResponse {
    #[prost(message, optional, tag="1")]
    pub view: ::core::option::Option<View>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetViewLevelRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub level: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetViewLevelResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExploreTreeNode {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub level_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="4")]
    pub level: i32,
    #[prost(message, optional, tag="5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int32, optional, tag="6")]
    pub parent_view_id: ::core::option::Option<i32>,
}
// ── GetWorkspace ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWorkspaceRequest {
    /// Required. UUID of the organisation.
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    /// Optional. Filter by owner element ID.
    #[prost(int32, optional, tag="2")]
    pub parent_id: ::core::option::Option<i32>,
    /// Optional. Filter by abstraction level.
    #[prost(int32, optional, tag="3")]
    pub level: ::core::option::Option<i32>,
    /// Optional. Search string for view name.
    #[prost(string, optional, tag="4")]
    pub search: ::core::option::Option<::prost::alloc::string::String>,
    /// Optional. Pagination limit.
    #[prost(int32, tag="5")]
    pub limit: i32,
    /// Optional. Pagination offset.
    #[prost(int32, tag="6")]
    pub offset: i32,
    /// Optional. If true, include placements, connectors and navigations for the returned views.
    #[prost(bool, tag="7")]
    pub include_content: bool,
    /// Optional. API key for request-level authentication.
    #[prost(string, optional, tag="8")]
    pub api_key: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWorkspaceResponse {
    #[prost(message, repeated, tag="1")]
    pub views: ::prost::alloc::vec::Vec<View>,
    #[prost(int32, tag="2")]
    pub total_count: i32,
    /// Populated if include_content is true in request.
    /// Map of view_id -> view content (placements, connectors).
    #[prost(map="int32, message", tag="3")]
    pub content: ::std::collections::HashMap<i32, ViewContent>,
    #[prost(message, repeated, tag="4")]
    pub navigations: ::prost::alloc::vec::Vec<ElementNavigationInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IncomingElementNavigationInfo {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
    #[prost(string, tag="3")]
    pub element_name: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub from_view_id: i32,
    #[prost(string, tag="5")]
    pub from_view_name: ::prost::alloc::string::String,
    #[prost(int32, tag="6")]
    pub to_view_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListIncomingElementNavigationsRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListIncomingElementNavigationsResponse {
    #[prost(message, repeated, tag="1")]
    pub navigations: ::prost::alloc::vec::Vec<IncomingElementNavigationInfo>,
}
// ── Elements ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListElementsRequest {
    #[prost(int32, tag="1")]
    pub limit: i32,
    #[prost(int32, tag="2")]
    pub offset: i32,
    #[prost(string, tag="3")]
    pub search: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListElementsResponse {
    #[prost(message, repeated, tag="1")]
    pub elements: ::prost::alloc::vec::Vec<Element>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetElementRequest {
    #[prost(int32, tag="1")]
    pub element_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetElementResponse {
    #[prost(message, optional, tag="1")]
    pub element: ::core::option::Option<Element>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateElementRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="7")]
    pub technology_links: ::prost::alloc::vec::Vec<TechnologyLink>,
    #[prost(string, repeated, tag="8")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="9")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateElementResponse {
    #[prost(message, optional, tag="1")]
    pub element: ::core::option::Option<Element>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateElementRequest {
    #[prost(int32, tag="1")]
    pub element_id: i32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub technology: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub logo_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="8")]
    pub technology_links: ::prost::alloc::vec::Vec<TechnologyLink>,
    #[prost(string, repeated, tag="9")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub repo: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub branch: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="13")]
    pub file_path: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateElementResponse {
    #[prost(message, optional, tag="1")]
    pub element: ::core::option::Option<Element>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ViewPlacementInfo {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(string, tag="2")]
    pub view_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListElementPlacementsRequest {
    #[prost(int32, tag="1")]
    pub element_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListElementPlacementsResponse {
    #[prost(message, repeated, tag="1")]
    pub placements: ::prost::alloc::vec::Vec<ViewPlacementInfo>,
}
// ── Placements ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPlacementsRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPlacementsResponse {
    #[prost(message, repeated, tag="1")]
    pub placements: ::prost::alloc::vec::Vec<PlacedElement>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CreatePlacementRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
    #[prost(double, tag="3")]
    pub position_x: f64,
    #[prost(double, tag="4")]
    pub position_y: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePlacementResponse {
    #[prost(message, optional, tag="1")]
    pub placement: ::core::option::Option<PlacedElement>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdatePlacementPositionRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
    #[prost(double, tag="3")]
    pub position_x: f64,
    #[prost(double, tag="4")]
    pub position_y: f64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePlacementPositionResponse {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePlacementRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePlacementResponse {
}
// ── Connectors ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListConnectorsRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConnectorsResponse {
    #[prost(message, repeated, tag="1")]
    pub connectors: ::prost::alloc::vec::Vec<Connector>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectorRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub source_element_id: i32,
    #[prost(int32, tag="3")]
    pub target_element_id: i32,
    #[prost(string, optional, tag="4")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="5")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub relationship: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="7")]
    pub direction: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub style: ::prost::alloc::string::String,
    #[prost(string, optional, tag="9")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="10")]
    pub source_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub target_handle: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateConnectorResponse {
    #[prost(message, optional, tag="1")]
    pub connector: ::core::option::Option<Connector>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConnectorRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub connector_id: i32,
    #[prost(int32, optional, tag="3")]
    pub source_element_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="4")]
    pub target_element_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag="5")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="7")]
    pub relationship: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub direction: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub style: ::prost::alloc::string::String,
    #[prost(string, optional, tag="10")]
    pub url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub source_handle: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="12")]
    pub target_handle: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConnectorResponse {
    #[prost(message, optional, tag="1")]
    pub connector: ::core::option::Option<Connector>,
}
// ── Element Navigations ──────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ElementNavigationInfo {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, optional, tag="2")]
    pub element_id: ::core::option::Option<i32>,
    #[prost(int32, tag="3")]
    pub from_view_id: i32,
    #[prost(int32, tag="4")]
    pub to_view_id: i32,
    #[prost(string, tag="5")]
    pub to_view_name: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub relation_type: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListElementNavigationsRequest {
    #[prost(int32, tag="1")]
    pub element_id: i32,
    #[prost(int32, optional, tag="2")]
    pub from_view_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub to_view_id: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListElementNavigationsResponse {
    #[prost(message, repeated, tag="1")]
    pub navigations: ::prost::alloc::vec::Vec<ElementNavigationInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateElementNavigationRequest {
    #[prost(int32, tag="1")]
    pub element_id: i32,
    #[prost(int32, tag="2")]
    pub from_view_id: i32,
    #[prost(int32, tag="3")]
    pub to_view_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateElementNavigationResponse {
    #[prost(message, optional, tag="1")]
    pub navigation: ::core::option::Option<ElementNavigationInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementNavigationByIdRequest {
    #[prost(int32, tag="1")]
    pub navigation_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteElementNavigationByIdResponse {
}
// ── View Layers ──────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ViewLayer {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(int32, tag="2")]
    pub view_id: i32,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub color: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListViewLayersRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListViewLayersResponse {
    #[prost(message, repeated, tag="1")]
    pub layers: ::prost::alloc::vec::Vec<ViewLayer>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateViewLayerRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="4")]
    pub color: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateViewLayerResponse {
    #[prost(message, optional, tag="1")]
    pub layer: ::core::option::Option<ViewLayer>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateViewLayerRequest {
    #[prost(int32, tag="1")]
    pub layer_id: i32,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="3")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub color: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateViewLayerResponse {
    #[prost(message, optional, tag="1")]
    pub layer: ::core::option::Option<ViewLayer>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteViewLayerRequest {
    #[prost(int32, tag="1")]
    pub layer_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteViewLayerResponse {
}
// ── Comment Threads ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommentInfo {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub view_id: i32,
    #[prost(int32, tag="4")]
    pub thread_id: i32,
    #[prost(string, tag="5")]
    pub author_id: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub author_username: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreadInfo {
    #[prost(int32, tag="1")]
    pub id: i32,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub view_id: i32,
    #[prost(int32, optional, tag="4")]
    pub element_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="5")]
    pub connector_id: ::core::option::Option<i32>,
    #[prost(string, tag="6")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub created_by_username: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="10")]
    pub resolved_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag="11")]
    pub comments: ::prost::alloc::vec::Vec<CommentInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListThreadsRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, optional, tag="2")]
    pub element_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub connector_id: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListThreadsResponse {
    #[prost(message, repeated, tag="1")]
    pub threads: ::prost::alloc::vec::Vec<ThreadInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateThreadRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, optional, tag="2")]
    pub element_id: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="3")]
    pub connector_id: ::core::option::Option<i32>,
    #[prost(string, tag="4")]
    pub body: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateThreadResponse {
    #[prost(message, optional, tag="1")]
    pub thread: ::core::option::Option<ThreadInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddCommentRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub thread_id: i32,
    #[prost(string, tag="3")]
    pub body: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddCommentResponse {
    #[prost(message, optional, tag="1")]
    pub comment: ::core::option::Option<CommentInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveThreadRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub thread_id: i32,
    #[prost(bool, tag="3")]
    pub resolved: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveThreadResponse {
}
// ── Reactions ────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NodeReactionSummary {
    #[prost(int32, tag="1")]
    pub element_id: i32,
    #[prost(string, tag="2")]
    pub emoji: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub count: i32,
    #[prost(bool, tag="4")]
    pub reacted_by_me: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListReactionsRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReactionsResponse {
    #[prost(message, repeated, tag="1")]
    pub reactions: ::prost::alloc::vec::Vec<NodeReactionSummary>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToggleReactionRequest {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(int32, tag="2")]
    pub element_id: i32,
    #[prost(string, tag="3")]
    pub emoji: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ToggleReactionResponse {
    #[prost(bool, tag="1")]
    pub active: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportResourcesRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub elements: ::prost::alloc::vec::Vec<PlanElement>,
    #[prost(message, repeated, tag="3")]
    pub connectors: ::prost::alloc::vec::Vec<PlanConnector>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImportResourcesResponse {
    #[prost(int32, tag="1")]
    pub view_id: i32,
    #[prost(string, tag="2")]
    pub view_url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ParseStructurizrRequest {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseStructurizrResponse {
    #[prost(message, repeated, tag="1")]
    pub elements: ::prost::alloc::vec::Vec<PlanElement>,
    #[prost(message, repeated, tag="2")]
    pub connectors: ::prost::alloc::vec::Vec<PlanConnector>,
    #[prost(string, repeated, tag="3")]
    pub warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotificationItem {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub body: ::prost::alloc::string::String,
    #[prost(message, optional, tag="7")]
    pub metadata: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, optional, tag="8")]
    pub read_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListNotificationsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListNotificationsResponse {
    #[prost(message, repeated, tag="1")]
    pub notifications: ::prost::alloc::vec::Vec<NotificationItem>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkNotificationReadRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkNotificationReadResponse {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAllNotificationsReadRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAllNotificationsReadResponse {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeedOrganizationRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeedOrganizationResponse {
}
// ── Organization ─────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Organization {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub plan: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub trial_started_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="6")]
    pub trial_ends_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(bool, tag="7")]
    pub trial_used: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrganizationRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrganizationResponse {
    #[prost(message, optional, tag="1")]
    pub organization: ::core::option::Option<Organization>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationResponse {
    #[prost(message, optional, tag="1")]
    pub organization: ::core::option::Option<Organization>,
}
// ── Usage ────────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsageCounter {
    #[prost(int32, optional, tag="1")]
    pub used: ::core::option::Option<i32>,
    #[prost(int32, optional, tag="2")]
    pub limit: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageResponse {
    #[prost(message, optional, tag="1")]
    pub diagrams: ::core::option::Option<UsageCounter>,
    #[prost(message, optional, tag="2")]
    pub objects: ::core::option::Option<UsageCounter>,
    #[prost(message, optional, tag="3")]
    pub members: ::core::option::Option<UsageCounter>,
    #[prost(message, optional, tag="4")]
    pub editors: ::core::option::Option<UsageCounter>,
    #[prost(bool, tag="5")]
    pub is_read_only: bool,
    #[prost(string, tag="6")]
    pub effective_plan: ::prost::alloc::string::String,
}
// ── Members ──────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OrgMember {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub role: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub joined_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag="6")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, optional, tag="7")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMembersRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMembersResponse {
    #[prost(message, repeated, tag="1")]
    pub members: ::prost::alloc::vec::Vec<OrgMember>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateMemberRoleRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub role: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateMemberRoleResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveMemberRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveMemberResponse {
}
// ── Invitations ──────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Invitation {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub invited_by: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub status: ::prost::alloc::string::String,
    #[prost(message, optional, tag="8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="9")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateInvitationRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub role: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateInvitationResponse {
    /// If user existed and was added directly, member is set.
    #[prost(message, optional, tag="1")]
    pub member: ::core::option::Option<OrgMember>,
    /// If invitation was created, invitation is set.
    #[prost(message, optional, tag="2")]
    pub invitation: ::core::option::Option<Invitation>,
    #[prost(string, tag="3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListInvitationsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInvitationsResponse {
    #[prost(message, repeated, tag="1")]
    pub invitations: ::prost::alloc::vec::Vec<Invitation>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteInvitationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteInvitationResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResendInvitationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResendInvitationResponse {
}
// ── API Keys ─────────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApiKey {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub key_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub last_used_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatedApiKey {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub key_prefix: ::prost::alloc::string::String,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub last_used_at: ::core::option::Option<::prost_types::Timestamp>,
    /// plaintext key - shown once, never stored.
    #[prost(string, tag="8")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListApiKeysRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiKeysResponse {
    #[prost(message, repeated, tag="1")]
    pub api_keys: ::prost::alloc::vec::Vec<ApiKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateApiKeyRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateApiKeyResponse {
    #[prost(message, optional, tag="1")]
    pub api_key: ::core::option::Option<CreatedApiKey>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeApiKeyRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeApiKeyResponse {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Tag {
    #[prost(string, tag="1")]
    pub color: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTagColorsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTagColorsResponse {
    /// Map of tag name to tag info
    #[prost(map="string, message", tag="1")]
    pub tags: ::std::collections::HashMap<::prost::alloc::string::String, Tag>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTagRequest {
    #[prost(string, tag="1")]
    pub tag: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub color: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTagResponse {
}
// ── Change Password ──────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangePasswordRequest {
    #[prost(string, tag="1")]
    pub old_password: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub new_password: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangePasswordResponse {
}
// ── List Organizations ───────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListOrganizationsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsResponse {
    #[prost(message, repeated, tag="1")]
    pub organizations: ::prost::alloc::vec::Vec<OrgInfo>,
}
// ── Switch Organization ──────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SwitchOrganizationRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SwitchOrganizationResponse {
    #[prost(message, optional, tag="1")]
    pub org: ::core::option::Option<OrgInfo>,
}
// ── Preferences ──────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPreferencesRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPreferencesResponse {
    #[prost(string, optional, tag="1")]
    pub accent_color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub background_color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub object_color: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePreferencesRequest {
    #[prost(string, optional, tag="1")]
    pub accent_color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="2")]
    pub background_color: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub object_color: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdatePreferencesResponse {
}
// ── Delete Preview ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockingOrg {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub members: ::prost::alloc::vec::Vec<BlockingOrgMember>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockingOrgMember {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub username: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePreviewRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePreviewResponse {
    #[prost(message, repeated, tag="1")]
    pub blocking_orgs: ::prost::alloc::vec::Vec<BlockingOrg>,
    #[prost(string, repeated, tag="2")]
    pub pro_subscription_org_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
// ── Transfer Org Ownership ───────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferOrgOwnershipRequest {
    #[prost(string, tag="1")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub new_owner_user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TransferOrgOwnershipResponse {
}
// ── Delete Account ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAccountRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteAccountResponse {
}
// ── Workspace Version ────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkspaceVersionInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub org_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, optional, tag="5")]
    pub parent_version_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag="6")]
    pub view_count: i32,
    #[prost(int32, tag="7")]
    pub element_count: i32,
    #[prost(int32, tag="8")]
    pub connector_count: i32,
    #[prost(string, optional, tag="10")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="11")]
    pub workspace_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="12")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
// ── List Versions ────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListVersionsRequest {
    #[prost(int32, tag="1")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListVersionsResponse {
    #[prost(message, repeated, tag="1")]
    pub versions: ::prost::alloc::vec::Vec<WorkspaceVersionInfo>,
}
// ── Get Latest ───────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLatestVersionRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLatestVersionResponse {
    #[prost(message, optional, tag="1")]
    pub version: ::core::option::Option<WorkspaceVersionInfo>,
}
// ── Create Version ───────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateVersionRequest {
    #[prost(string, tag="1")]
    pub version_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub workspace_hash: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateVersionResponse {
    #[prost(message, optional, tag="1")]
    pub version: ::core::option::Option<WorkspaceVersionInfo>,
}
// ── Settings ─────────────────────────────────────────────────────────────

#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVersionSettingsRequest {
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVersionSettingsResponse {
    #[prost(bool, tag="1")]
    pub cli_versioning_enabled: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateVersionSettingsRequest {
    #[prost(bool, tag="1")]
    pub cli_versioning_enabled: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateVersionSettingsResponse {
    #[prost(bool, tag="1")]
    pub cli_versioning_enabled: bool,
}
include!("diag.v1.tonic.rs");
// @@protoc_insertion_point(module)