// Generated by buf generate — do not edit by hand.
// Source: proto/proto/diag/v1/*.proto
//
// Regenerate with:
//   cd proto && buf generate          (from the diag monorepo root)
//   make generate                      (from the proto/ repo)
//
// The prost file (diag.v1.rs) already includes diag.v1.tonic.rs via a
// protoc insertion point at the end — do not include the tonic file again here.

pub mod diag {
    pub mod v1 {
        // prost message structs + tonic service clients (tonic file is included
        // at the end of the prost file via protoc insertion point)
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/diag/v1/diag.v1.rs"
        ));
    }
}

/// Convenience re-export: `diag_proto::diagv1::WorkspaceServiceClient`, etc.
pub use diag::v1 as diagv1;
